#!/bin/sh
### GIT
git config --global core.autocrlf false
git config --global credential.helper manager-core
git config --global core.editor nvim
git config --global core.editor.nvim.path "/usr/bin/nvim"
git config --global diff.tool nvim
git config --global diff.tool.nvim.path "/usr/bin/nvim"
git config --global diff.tool.nvim.cmd "nvim -d \"$local\" \"$remote\""
git config --global init.default.branch main
git config --global core.fsmonitor false

# set up environment, depending on os
if grep -qi microsoft /proc/version
then
  echo "ubuntu on wsl"
elif grep -qi ubuntu /proc/version ; then
  echo "native ubuntu linux"
fi

# Make neovim the default editor.
export EDITOR='nvim';

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
#export GPG_TTY=$(tty);

# Hide the “default interactive shell is now zsh” warning on macOS.
#export BASH_SILENCE_DEPRECATION_WARNING=1;

### ANTIGEN
# SOURCE_RCFILE $ZSH_CONFIG_HOME/.zsh_antigenrc

### ANTIDOTE
SOURCE_RCFILE $ZSH_CONFIG_HOME/zsh_antidoterc

### Initialize CARGO
EXPORT_DIR $HOME/.cargo/bin

### GITHUB repos exports
[ -d ~/gitdepot ] && gitdepot=~/gitdepot

# TTY theme
# SOURCE_RCFILE $ZSH_CONFIG_HOME/catppuccin_tty/mocha.sh
SOURCE_RCFILE $gitdepot/dracula_tty/dracula-tty.sh

### Zoxide
if command -v zoxide &> /dev/null
then
  eval "$(zoxide init zsh)" 
fi

# user-s bin path
EXPORT_DIR $HOME/.local/bin
# bat extras scripts
EXPORT_DIR $HOME/gitdepot/bat-extras/src

# btop
### Initialize Starship
if command -v starship &>/dev/null
then
  eval "$(starship init zsh)"
fi
