[options]
automatic_update = true
bootstrap_after = 'myspacevim#after'
bootstrap_before = 'myspacevim#before'
colorscheme = 'catppuccin-mocha'
enable_guicolors = true
enable_statusline_mode = true
enable_tabline_filetype_icon = true
escape_key_binding = 'kj'
[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"
[[layers]]
name = 'colorscheme'
[[layers]]
name = "default"
[[layers]]
name = "denite"
[[layers]]
name = "format"
format_method = "neoformat"
format_on_save = true
[[layers]]
name = "fzf"
[[layers]]
name = 'git'
[[layers]]
name = 'lsp'
enabled_clients = ['jdtls', 'clangd']
[[layers]]
name = "shell"
default_position = "top"
default_height = 30
enable = false
[[layers]]
name = "sudo"
[[layers]]
name = "telescope"
[[layers]]
name = "tmux"
tmux_navigator_modifier = "alt"
[[layers]]
name = 'VersionControl'
[[layers]]
name = 'vim'
[[layers]]
name = "lang#json"
[[layers]]
name = "lang#lua"
[[layers]]
name = "lang#markdown"
[[layers]]
name = "lang#python"
[[layers]]
name = "lang#sh"
[[layers]]
name = "lang#toml"
[[layers]]
name = "lang#vim"
bash_file_head = [
  '#!/usr/bin/env bash',
  '#!/usr/bin/env zsh',
  '#!/usr/bin/env sh',
  '',
]
[[layers]]
name = "lang#xml"
[[layers]]
name = "lang#yaml"
[[custom_plugins]]
repo = 'lilydjwg/colorizer'
# `on_cmd` option means this plugin will be loaded
# only when the specific commands are called.
# for example, when `:ColorHighlight` or `:ColorToggle`
# commands are called.
on_cmd = ['ColorHighlight', 'ColorToggle']
# `on_func` option means this plugin will be loaded
# only when the specific functions are called.
# for example, when `colorizer#ColorToggle()` function is called.
on_func = 'colorizer#ColorToggle'
# `merged` option is used for merging plugins directory.
# When `merged` is `true`, all files in this custom plugin
# will be merged into `~/.cache/vimfiles/.cache/init.vim/`
# for neovim or `~/.cache/vimfiles/.cache/vimrc/` for vim.
merged = false
# For more options see `:h dein-options`.
[[custom_plugins]]
repo = 'catppuccin/nvim'
merged = false
[[custom_plugins]]
name = 'ryanoasis/vim-devicons'
