nnoremap <silent> <leader>tf :Files<CR>
nnoremap <silent> <leader>tb :Buffers<CR>
nnoremap <silent> <leader>tm :Maps<CR>
nnoremap <silent> <leader>tt :Tags<CR>
nnoremap <silent> <leader>tr :History:<CR>
nnoremap <silent> <leader>tF :History/<CR>
nnoremap <silent> <leader>tG :Commits<CR>
nnoremap <silent> <leader>tn :Snippets<CR>
nnoremap <silent> <leader>th :helptags<CR>
nnoremap <silent> <leader>tk :Commands<CR>
nnoremap <silent> <leader>tg :Rg<CR>
nnoremap <silent> <leader>tl :BLines<CR>
