#!/bin/zsh
# vim: ft=zsh

# else function
# Usage: else_ [-h] [-m <message>]
# Runs if the previous command (try) succeeded.
# -h: Displays help for the else function.
# -m <message>: Specifies a custom success message.
else_() {
    if [[ "$1" == "-h" ]]; then
        echo "Usage: else_ [-m <message>]\nRuns if the try command was successful."
        return
    fi

    local custom_message="Command executed successfully."
    while getopts "m:" opt; do
        case $opt in
            m) custom_message="$OPTARG";;
            *) echo "Invalid option"; return 1;;
        esac
    done

    if (( _TRY_EXIT_CODE == 0 )); then
        echo "$custom_message"
    fi
}

# Save this script to a file named `$ZDOTDIR/functions/else_`.
