#!/bin/zsh
# vim: ft=zsh

# except function
# Usage: except [-h] [-m <message>]
# Runs if the previous command (try) failed.
# -h: Displays help for the except function.
# -m <message>: Specifies a custom message to display if an error occurred.
except_() {
    if [[ "$1" == "-h" ]]; then
        echo "Usage: except [-m <message>]\nHandles errors if the try function failed."
        return
    fi

    local custom_message="An error occurred."
    while getopts "m:" opt; do
        case $opt in
            m) custom_message="$OPTARG";;
            *) echo "Invalid option"; return 1;;
        esac
    done

    if (( _TRY_EXIT_CODE != 0 )); then
        echo "$custom_message (Exit code: $_TRY_EXIT_CODE)"
    fi
}

# Save this script to a file named `$ZDOTDIR/functions/except`.
