#!/usr/bin/env bash

set -o pipefail
if [[ -n "$DEBUG" ]]; then
  set -x
fi

fail() {
  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
}

has() {
  which "$@" > /dev/null 2>&1
}

if has bat; then
  fzf-find-edit() {
    file=$(
      fd --type f --hidden --follow --exclude .git -E "node_modules" -I -g "$1" | \
      fzf --no-multi --select-1 --exit-0 \
        --preview 'bat --color=always --line-range :500 {}'
      )
    if [[ -n "$file" ]]; then
      $EDITOR "$file"
    fi
  }
else
  # No bat installed, so use head
  fzf-find-edit() {
    file=$(
      fd --type f --hidden --follow --exclude .git -E "node_modules" -I -g "$1" | \
      fzf --no-multi --select-1 --exit-0 \
        --preview 'less -N -S -R -+F -+X -M {}' # --preview 'head -100 {}'
      )
    if [[ -n "$file" ]]; then
      $EDITOR "$file"
    fi
  }
fi

# shellcheck disable=SC2068
fzf-find-edit $@
