#!/bin/env zsh

#Fuzzy find random file and open it with vi/vim/neovim

if [ ! command -v fzf &>/dev/null ] || [ ! command -v rg &>/dev/null ] ; then
  echocat "fzf and/or rg not installed, unable to declare fzf-rg-find()" -i
  return 1
fi

fzf-rg-find() {
  if command -v fd &>/dev/null; then
    vi $(fd --type f --unrestricted . --regex './' | fzf)
  else
    echocat "rg not installed, using find (fzf-rg-find())" -i
    vi $(find . -regextype sed -regex '/' -type f | fzf)
  fi
}
