#!/bin/env zsh


if [ ! command -v fzf &>/dev/null ] || [ ! command -v rg &>/dev/null ] ; then
  echocat "fzf and/or rg not installed, unable to declare fzf-rg-find()" -i
  return 1
fi
fzf-rg-search() {
    vi $(rg --hidden . | fzf | cut -d ':' -f 1)
}
